live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Delugia Mono"
style = "Bold"

[font.bold_italic]
family = "Delugia Mono"
style = "Bold Italic"

[font.italic]
family = "Delugia Mono"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Control"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 132
lines = 24

[window.padding]
x = 20
y = 5
